Aproximación por diferencias finitas para el cálculo de campo eléctrico para geometrías cuadradas 

# Generar una matriz N+2 x M+2 (Caso de matriz cuadrada/rectangular), se debe afirmar que los puntos están equidistantes y homogeneamente distribuidos.

El usuario debe ingresar las dimensiones de la matriz, así como el número de puntos para que el sistema cree la malla.

In [1]:
import numpy as np

n = int(input("Ingrese el número de filas equi-espaciados: "))
m = int(input("Ingrese el número de columnas equi-espaciados: "))
print("El número de puntos equidistantes a estudiar es: ", n*m)
print("La dimensión de su malla es de: ", (n+2)*(m+2), " contando condiciones de frontera")

Ingrese el número de filas equi-espaciados: 5
Ingrese el número de columnas equi-espaciados: 5
El número de puntos equidistantes a estudiar es:  25
La dimensión de su malla es de:  49  contando condiciones de frontera


# Definir las condiciones iniciales

## ¿Dónde voy a poner el potencial?

In [2]:
numero_fronteras = int(input("Escriba el # de fronteras a considerar (solo si son distintas de 0): "))
if numero_fronteras == 0 or numero_fronteras > 4:
    print("Error, el # de fronteras debe ser estar entre 0<numero_fronteras<=4")
    pass

Escriba el # de fronteras a considerar (solo si son distintas de 0): 4


## ¿Dónde ubicar las fronteras?

In [3]:
lista_ubicaciones = []
if numero_fronteras == 4:
    lista_ubicaciones = ["arriba", "abajo", "izquierda", "derecha"]
else:
    for i in range(numero_fronteras):
        frontera = str(input("Escriba la ubicación (arriba, abajo, izquierda, derecha), recuerde que no puede repetir: "))
        lista_ubicaciones.append(frontera)
print(lista_ubicaciones)

['arriba', 'abajo', 'izquierda', 'derecha']


## Rellenar la matriz

In [4]:
lista_numerica = []
for i in range(len(lista_ubicaciones)):
    valor_numerico = float(input("Ingrese un valor para " + str(lista_ubicaciones[i] + " ")))
    lista_numerica.append(valor_numerico)
print(lista_numerica)

Ingrese un valor para arriba 100
Ingrese un valor para abajo 200
Ingrese un valor para izquierda 300
Ingrese un valor para derecha 0
[100.0, 200.0, 300.0, 0.0]


## Codigo de condicionales que verifica la existencia de palabras en las listas y les asigna su valor numerico.

In [5]:
matriz_principal = np.zeros((n+2,m+2))

print(matriz_principal)

if "arriba" in lista_ubicaciones:
    arriba_ubicacion = lista_ubicaciones.index("arriba")
    for i in range(np.shape(matriz_principal)[1]):
        matriz_principal[0][i] = lista_numerica[arriba_ubicacion]
        
if "abajo" in lista_ubicaciones:
    abajo_ubicacion = lista_ubicaciones.index("abajo")
    for i in range(np.shape(matriz_principal)[1]):
        matriz_principal[n+1][i] = lista_numerica[abajo_ubicacion]
        
if "izquierda" in lista_ubicaciones:
    izquierda_ubicacion = lista_ubicaciones.index("izquierda")
    for i in range(np.shape(matriz_principal)[0]):
        matriz_principal[i][0] = lista_numerica[izquierda_ubicacion]
        
if "derecha" in lista_ubicaciones:
    derecha_ubicacion = lista_ubicaciones.index("derecha")
    for i in range(np.shape(matriz_principal)[0]):
        matriz_principal[i][m+1] = lista_numerica[derecha_ubicacion]
matriz_principal

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


array([[300., 100., 100., 100., 100., 100.,   0.],
       [300.,   0.,   0.,   0.,   0.,   0.,   0.],
       [300.,   0.,   0.,   0.,   0.,   0.,   0.],
       [300.,   0.,   0.,   0.,   0.,   0.,   0.],
       [300.,   0.,   0.,   0.,   0.,   0.,   0.],
       [300.,   0.,   0.,   0.,   0.,   0.,   0.],
       [300., 200., 200., 200., 200., 200.,   0.]])

In [6]:
#ciclo hasta m+1 ya que no toma el valor límite de m con el range()
contador = 1.0
for i in range(1,n+1):
    for j in range(1,m+1):
        matriz_principal[i][j]=contador 
        contador += 1.0
print(matriz_principal)

[[300. 100. 100. 100. 100. 100.   0.]
 [300.   1.   2.   3.   4.   5.   0.]
 [300.   6.   7.   8.   9.  10.   0.]
 [300.  11.  12.  13.  14.  15.   0.]
 [300.  16.  17.  18.  19.  20.   0.]
 [300.  21.  22.  23.  24.  25.   0.]
 [300. 200. 200. 200. 200. 200.   0.]]


# Generar la matriz de coeficientes basados en la placa con voltajes

Crear una matriz diagonal de n x m, cuya diagonal principal está compuesta del valor -4 (Laplace)

In [7]:
diagonal_principal = np.ones(n*m)*-4.0
np.shape(diagonal_principal)

(25,)

In [8]:
matriz_de_coeficientes = np.diag(diagonal_principal)
print(matriz_de_coeficientes)

[[-4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0. -4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -4.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -4.  0.  0.  0.  

## Dada la configuración del sistema es importante conocer el último punto de la submatriz nxm que contiene los voltajes que se busca hallar.

In [9]:
ultimo_punto = matriz_principal[n][m]

In [10]:
ultimo_punto_matriz_coeficientes = matriz_de_coeficientes[(n*m)-1][(n*m)-1]

## Algoritmo para extraer los 4 vecinos más próximos de cada uno de los puntos de  voltaje.

In [11]:
#Algoritmo simple para extracción de los vecinos del primer punto
vecinos = []

primer_voltaje = matriz_principal[1][1]
print("el primer voltaje es: ", primer_voltaje)
counter = 0

#Ciclo anidado que saca los vecinos y los coloca en una lista, vienen en grupos de 4

for j in range(1,n+1):
    for i in range(1,m+1):
        arriba = matriz_principal[j-1-counter][i] 
        abajo = matriz_principal[j+1-counter][i]
        izquierda = matriz_principal[j-counter][i-1]
        derecha = matriz_principal[j-counter][i+1]
        counter += 1
        if counter % m-1 == 0:
            counter = 0
        vecinos.append(arriba)
        vecinos.append(abajo)
        vecinos.append(izquierda)
        vecinos.append(derecha)
    
print(vecinos)

el primer voltaje es:  1.0
[100.0, 6.0, 300.0, 2.0, 100.0, 7.0, 1.0, 3.0, 100.0, 8.0, 2.0, 4.0, 100.0, 9.0, 3.0, 5.0, 100.0, 10.0, 4.0, 0.0, 1.0, 11.0, 300.0, 7.0, 2.0, 12.0, 6.0, 8.0, 3.0, 13.0, 7.0, 9.0, 4.0, 14.0, 8.0, 10.0, 5.0, 15.0, 9.0, 0.0, 6.0, 16.0, 300.0, 12.0, 7.0, 17.0, 11.0, 13.0, 8.0, 18.0, 12.0, 14.0, 9.0, 19.0, 13.0, 15.0, 10.0, 20.0, 14.0, 0.0, 11.0, 21.0, 300.0, 17.0, 12.0, 22.0, 16.0, 18.0, 13.0, 23.0, 17.0, 19.0, 14.0, 24.0, 18.0, 20.0, 15.0, 25.0, 19.0, 0.0, 16.0, 200.0, 300.0, 22.0, 17.0, 200.0, 21.0, 23.0, 18.0, 200.0, 22.0, 24.0, 19.0, 200.0, 23.0, 25.0, 20.0, 200.0, 24.0, 0.0]


## Crear la lista de listas que contiene los vecinos de cada uno de los puntos de voltaje

In [12]:
#separar la lista en una lista de listas
def split_list (lista_entrada, x):
   return [lista_entrada[i:i+x] for i in range(0, len(lista_entrada), x)]

lista_coeficientes = split_list(vecinos, 4)
print(lista_coeficientes)

[[100.0, 6.0, 300.0, 2.0], [100.0, 7.0, 1.0, 3.0], [100.0, 8.0, 2.0, 4.0], [100.0, 9.0, 3.0, 5.0], [100.0, 10.0, 4.0, 0.0], [1.0, 11.0, 300.0, 7.0], [2.0, 12.0, 6.0, 8.0], [3.0, 13.0, 7.0, 9.0], [4.0, 14.0, 8.0, 10.0], [5.0, 15.0, 9.0, 0.0], [6.0, 16.0, 300.0, 12.0], [7.0, 17.0, 11.0, 13.0], [8.0, 18.0, 12.0, 14.0], [9.0, 19.0, 13.0, 15.0], [10.0, 20.0, 14.0, 0.0], [11.0, 21.0, 300.0, 17.0], [12.0, 22.0, 16.0, 18.0], [13.0, 23.0, 17.0, 19.0], [14.0, 24.0, 18.0, 20.0], [15.0, 25.0, 19.0, 0.0], [16.0, 200.0, 300.0, 22.0], [17.0, 200.0, 21.0, 23.0], [18.0, 200.0, 22.0, 24.0], [19.0, 200.0, 23.0, 25.0], [20.0, 200.0, 24.0, 0.0]]


In [13]:
# creación vector p
vector_p = np.zeros((n*m,1))
vector_p

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [14]:
print(matriz_principal[0][1])
print(matriz_principal[n+1][1])
print(matriz_principal[1][0])
print(matriz_principal[1][m+1])


100.0
200.0
300.0
0.0


In [15]:


for i in range(0,n*m-1):
    sumador=0 
    for j in range(0,3):
        if lista_coeficientes[i][j]== matriz_principal[0][1] or lista_coeficientes[i][j]== matriz_principal[n+1][1] or lista_coeficientes[i][j]== matriz_principal[1][0] or lista_coeficientes[i][j]== matriz_principal[1][m+1]:
            sumador=lista_coeficientes[i][j]+sumador
            vector_p[i]=(-1)*sumador
vector_p



array([[-400.],
       [-100.],
       [-100.],
       [-100.],
       [-100.],
       [-300.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [-300.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [-300.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [-500.],
       [-200.],
       [-200.],
       [-200.],
       [   0.]])

In [16]:

for i in range(0,n*m-1):
    for j in range(0,3):
        if i != j and int(lista_coeficientes[i][j])< n*m:
            matriz_de_coeficientes[i][int(lista_coeficientes[i][j]-1)]=1
        else:
            pass
            
            

        
print(matriz_de_coeficientes)         

           

[[-4.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -4.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0. -4.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1. -4.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  1. -4.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0. -4.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  1. -4.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  1. -4.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0. -4.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  1. -4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -4.]]


In [51]:
import numpy as np
Potencial=[]
np.linalg.inv( matriz_de_coeficientes)
np.dot(np.linalg.inv( matriz_de_coeficientes),vector_p)

array([[  87.5       ],
       [-161.76470588],
       [-243.75      ],
       [-111.76470588],
       [-225.        ],
       [  47.05882353],
       [ 193.75      ],
       [  61.76470588],
       [ 143.75      ],
       [  11.76470588],
       [ 125.        ],
       [  50.        ],
       [  50.        ],
       [  50.        ],
       [  81.25      ]])